version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: job_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - db

  job-scraper:
    build: .
    container_name: job_scraper
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: job_db
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_PORT: 5432
    # This container will run once, execute the scraper, then exit.

volumes:
  postgres_data:
  metabase_data: